export const colorVars = {
  ink: "var(--ink)",
  inkSoft: "var(--ink-soft)",
  line: "var(--line)",
  lineSoft: "var(--line-soft)",
  white: "var(--white)",
  whiteSoft: "var(--white-soft)",
  teal: "var(--teal)",
  tealSoft: "var(--teal-soft)",
  clay: "var(--clay)",
  claySoft: "var(--clay-soft)",
  danger: "var(--danger)",
  chartNetWorth: "var(--chart-net-worth)",
  chartRetirement: "var(--chart-retirement)",
  chartCash: "var(--chart-cash)",
  chartRsus: "var(--chart-rsus)",
  chartOtherAssets: "var(--chart-other-assets)",
  chartHomeEquity: "var(--chart-home-equity)",
  chartTaxes: "var(--chart-taxes)",
  chartRetirementSavings: "var(--chart-retirement-savings)",
  chartHousing: "var(--chart-housing)",
  chartExpenses: "var(--chart-expenses)",
  chartExcess: "var(--chart-excess)",
} as const;

export const netWorthChartLegend = [
  { label: "Net worth", color: colorVars.chartNetWorth },
  { label: "Retirement", color: colorVars.chartRetirement },
  { label: "Cash", color: colorVars.chartCash },
  { label: "RSUs", color: colorVars.chartRsus },
  { label: "Other assets", color: colorVars.chartOtherAssets },
  { label: "Home equity", color: colorVars.chartHomeEquity },
] as const;
